//
// Created by Cyril on 17/08/2021.
//

#ifndef ORB_FIRMWARE_ORB_APP_BOARDS_STM32G4DISCOVERY_PLATFORM_STM32G4XX_CLOCKS_H
#define ORB_FIRMWARE_ORB_APP_BOARDS_STM32G4DISCOVERY_PLATFORM_STM32G4XX_CLOCKS_H

void
SystemClock_Config(void);

#endif //ORB_FIRMWARE_ORB_APP_BOARDS_STM32G4DISCOVERY_PLATFORM_STM32G4XX_CLOCKS_H
