stages:
  - build

build_all:
  stage: build
  only:
    - tags
  except:
    - branches
  image: gitlab/dind
  services:
    - docker:dind
  script:
    # build the Docker image
    - docker build utils/env -t worldcoin
    # run firmware build
    - docker run --rm -w=/home/project/firmware -v `pwd`:/home/project/firmware worldcoin make all
  artifacts:
    paths:
      - orb/app/boards/orb_v1/build/*.elf
      - orb/app/boards/stm32f3discovery/build/*.elf
    expire_in: 1 yrs