stages:
  - build

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build_all:
  stage: build
  only:
    - tags
  except:
    - branches
  image: gitlab/dind
  services:
    - docker:dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # build the Docker image
    - docker build utils/env -t worldcoin
    # run firmware build
    - docker run --rm -w=/home/project/firmware -v `pwd`:/home/project/firmware worldcoin make all
  artifacts:
    paths:
      - build/orb/app/boards/orb_v1/*.elf
      - build/orb/app/boards/stm32f3discovery/*.elf
    expire_in: 1 yrs