manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: eb2e718556715304891df12e54d24618bf85623c
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb

    - name: protobuf-definitions
      revision: ef4f268c5d88dea8f6275b5f26dada811a5af410
      path: modules/orb-protobuf-definitions
    - name: plug-and-trust
      revision: dc8923582abfb50840af9ce346a3cf4dd8ecf395
      path: modules/plug-and-trust
  self:
    path: orb
