manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: b69d1cedf617848332718a2f72384d9b2b077d5e
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.17.0
    - name: orb-messages
      revision: d303b8ae88c96559b08336fdbcdcc55e3ea27698
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 24b1543547649818bc236ecb9a1ed5794b7f57d0
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  group-filter: [-internal]
