manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
    - name: zenoh
      url-base: https://github.com/eclipse-zenoh/
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: 6ad5981031080f463d4b04dcf944aabe6458d306 # Zephyr 4.1.0 + patches on worldcoin/zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
          - zcbor
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.19.0
    - name: zenoh
      revision: 1.5.0
      remote: zenoh
      path: modules/lib/zenoh
    - name: orb-messages
      revision: 5ee5eb211e2947be3ef145bb4ee0d8ee76669f20
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 58da861808b3b8453c8998d3b1c3931a02286697
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: c4cf5f29027f44fd5aad1d896df5840e10b08fd4
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  # `optional` is used to fetch nanopb from the Zephyr west manifest
  group-filter: [-internal, +optional]
