manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: d356280b5432cad22983ad13aa154645187c37d1
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb

    - name: protobuf-definitions
      revision: bf272f61bc6685aaf040a28ea2a2f99726f4401a
      path: modules/orb-protobuf-definitions
  self:
    path: orb
