manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: ac1bf1b6c67c7abef0c4613aefce8662f71a38e4
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: orb-messages
      revision: 0cf4636b99211cdbebba3948776cbb8c351d45af
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: b2e01ac2c617cdbb1f1dc77ab49a4561d855cb11
      path: modules/orb-messages
      groups: [internal]
    - name: orb-security-mcu-firmware
      revision: cf4b52407536873ade6cfbdd91da8957cb932b33
      path: orb/sec_board
      groups: [internal]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  group-filter: [-internal]
