manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: ac1bf1b6c67c7abef0c4613aefce8662f71a38e4
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: orb-security-mcu-firmware
      revision: a74c9b1c2841780d9b13beb792200140f7b9df94
      path: orb/sec_board
      groups: [internal]
    - name: orb-mcu-messaging
      revision: 011ad102a5074675d6551867f7f433f9b3f028ef
      path: modules/orb-mcu-messaging
      submodules: true
      groups: [internal]
    - name: open-orb-mcu-messaging
      revision: 120921587747c712bd454196ac7941af2c2f3497
      path: modules/open-orb-mcu-messaging
      groups: [public]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
  self:
    path: orb
    import:
      # select groups in orb/utils/open/groups.yml, between [internal] and [public]
      - utils/open/groups.yml
