manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: pete
      url-base: git@github.com:pdietl
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      remote: pete
      revision: combined
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb

    - name: protobuf-definitions
      revision: main
      path: modules/orb-protobuf-definitions
  self:
    path: orb
