manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: d356280b5432cad22983ad13aa154645187c37d1
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb

    - name: protobuf-definitions
      revision: 3ee4a3c761ad9d29f7931ae5bf17565a8e46533f
      path: modules/orb-protobuf-definitions
  self:
    path: orb
