manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: 447c41c0729c0cbb4ca9fb6357d592c55c65a7b4
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.9.0 # 1.9.0
    - name: orb-messages
      revision: 1ebc148383587f9944bbb628bf4e8cbdea49058f
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 9c6ec2abb926ee3b428f1982fd6b1a8586834991
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  group-filter: [-internal]
