manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: f63949b8d21167409880ec856591a639a6dac613
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: protobuf-definitions
      revision: c4c11aa93ec18f875d51aef1cc0b8e66e6a6fac2
      path: modules/orb-protobuf-definitions
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
  self:
    path: orb
