manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: 98623d948f922dd17be62082fbd070233856c059 # Zephyr 4.1.0 + patches on worldcoin/zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
          - zcbor
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.19.0
    - name: orb-messages
      revision: 702de999f361458009247f0783e7b2dd71b22059
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 814f52429ced94c8180f3fbe17eeec1f1a01b556
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  # `optional` is used to fetch nanopb from the Zephyr west manifest
  group-filter: [-internal, +optional]
