manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: eb2e718556715304891df12e54d24618bf85623c
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: protobuf-definitions
      revision: a67bf98a760965d1344b75e3334398727551eecc
      path: modules/orb-protobuf-definitions
    - name: plug-and-trust
      revision: dc8923582abfb50840af9ce346a3cf4dd8ecf395
      path: modules/plug-and-trust
  self:
    path: orb
