manifest:
  projects:
    - name: canopennode
      url: https://github.com/zephyrproject-rtos/canopennode
      revision: f167efe85c8c7de886f1bc47f9173cfb8a346bb5
      path: modules/lib/canopennode
    - name: civetweb
      url: https://github.com/zephyrproject-rtos/civetweb
      revision: 094aeb41bb93e9199d24d665ee43e9e05d6d7b1c
      path: modules/lib/civetweb
    - name: cmsis
      url: https://github.com/zephyrproject-rtos/cmsis
      revision: b0612c97c1401feeb4160add6462c3627fe90fc7
      path: modules/hal/cmsis
      groups:
        - hal
    - name: edtt
      url: https://github.com/zephyrproject-rtos/edtt
      revision: 7dd56fc100d79cc45c33d43e7401d1803e26f6e7
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      url: https://github.com/zephyrproject-rtos/fatfs
      revision: 94fcd6bfb3801ac0a5e12ea2f52187e0a688b90e
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_altera
      url: https://github.com/zephyrproject-rtos/hal_altera
      revision: 23c1c1dd7a0c1cc9a399509d1819375847c95b97
      path: modules/hal/altera
      groups:
        - hal
    - name: hal_atmel
      url: https://github.com/zephyrproject-rtos/hal_atmel
      revision: 9f78f520f6cbb997e5b44fe8ab17dd5bf2448095
      path: modules/hal/atmel
      groups:
        - hal
    - name: hal_cypress
      url: https://github.com/zephyrproject-rtos/hal_cypress
      revision: 81a059f21435bc7e315bccd720da5a9b615bbb50
      path: modules/hal/cypress
      groups:
        - hal
    - name: hal_espressif
      url: https://github.com/zephyrproject-rtos/hal_espressif
      revision: 3400257534944d3a6a4194d1dbf8f0cd1670d64e
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
    - name: hal_infineon
      url: https://github.com/zephyrproject-rtos/hal_infineon
      revision: f1fa8241f8786198ba41155413243de36ed878a5
      path: modules/hal/infineon
      groups:
        - hal
    - name: hal_microchip
      url: https://github.com/zephyrproject-rtos/hal_microchip
      revision: 870d05e6a64ea9548da6b907058b03c8c9420826
      path: modules/hal/microchip
      groups:
        - hal
    - name: hal_nordic
      url: https://github.com/zephyrproject-rtos/hal_nordic
      revision: a6e5299041f152da5ae0ab17b2e44e088bb96d6d
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_nuvoton
      url: https://github.com/zephyrproject-rtos/hal_nuvoton
      revision: b4d31f33238713a568e23618845702fadd67386f
      path: modules/hal/nuvoton
      groups:
        - hal
    - name: hal_nxp
      url: https://github.com/zephyrproject-rtos/hal_nxp
      revision: 78efc4ba7c1057c1cf2bf06e3e27ed7cc33e1da7
      path: modules/hal/nxp
      groups:
        - hal
    - name: hal_openisa
      url: https://github.com/zephyrproject-rtos/hal_openisa
      revision: 40d049f69c50b58ea20473bee14cf93f518bf262
      path: modules/hal/openisa
      groups:
        - hal
    - name: hal_quicklogic
      url: https://github.com/zephyrproject-rtos/hal_quicklogic
      revision: b3a66fe6d04d87fd1533a5c8de51d0599fcd08d0
      path: modules/hal/quicklogic
      groups:
        - hal
    - name: hal_silabs
      url: https://github.com/zephyrproject-rtos/hal_silabs
      revision: be39d4eebeddac6e18e9c0c3ba1b31ad1e82eaed
      path: modules/hal/silabs
      groups:
        - hal
    - name: hal_st
      url: https://github.com/zephyrproject-rtos/hal_st
      revision: 575de9d461aa6f430cf62c58a053675377e700f3
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      url: https://github.com/zephyrproject-rtos/hal_stm32
      revision: 5c8275071ec1cf160bfe8c18bbd9330a7d714dc8
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_telink
      url: https://github.com/zephyrproject-rtos/hal_telink
      revision: ffcfd6282aa213f1dc0848dbca6279b098f6b143
      path: modules/hal/telink
      groups:
        - hal
    - name: hal_ti
      url: https://github.com/zephyrproject-rtos/hal_ti
      revision: 1992a4c536554c4f409c36896eda6abdc414d277
      path: modules/hal/ti
      groups:
        - hal
    - name: hal_xtensa
      url: https://github.com/zephyrproject-rtos/hal_xtensa
      revision: 6e1cf3c483e87df4888e87c5396b4534570f01af
      path: modules/hal/xtensa
      groups:
        - hal
    - name: libmetal
      url: https://github.com/zephyrproject-rtos/libmetal
      revision: 39d049d4ae68e6f6d595fce7de1dcfc1024fb4eb
      path: modules/hal/libmetal
      groups:
        - hal
    - name: littlefs
      url: https://github.com/zephyrproject-rtos/littlefs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
      path: modules/fs/littlefs
      groups:
        - fs
    - name: loramac-node
      url: https://github.com/zephyrproject-rtos/loramac-node
      revision: 12019623bbad9eb54fe51066847a7cbd4b4eac57
      path: modules/lib/loramac-node
    - name: lvgl
      url: https://github.com/zephyrproject-rtos/lvgl
      revision: 783c1f78c8e39751fe89d0883c8bce7336f55e94
      path: modules/lib/gui/lvgl
    - name: lz4
      url: https://github.com/zephyrproject-rtos/lz4
      revision: 8e303c264fc21c2116dc612658003a22e933124d
      path: modules/lib/lz4
    - name: mbedtls
      url: https://github.com/zephyrproject-rtos/mbedtls
      revision: 5765cb7f75a9973ae9232d438e361a9d7bbc49e7
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      url: https://github.com/zephyrproject-rtos/mcuboot
      revision: 70bfbd21cdf5f6d1402bc8d0031e197222ed2ec0
      path: bootloader/mcuboot
    - name: mcumgr
      url: https://github.com/zephyrproject-rtos/mcumgr
      revision: 31a2aa9cea58d3ceecbf0d5b91361bff7c94aeca
      path: modules/lib/mcumgr
    - name: mipi-sys-t
      url: https://github.com/zephyrproject-rtos/mipi-sys-t
      revision: 75e671550ac1acb502f315fe4952514dc73f7bfb
      path: modules/debug/mipi-sys-t
      groups:
        - debug
    - name: nanopb
      url: https://github.com/zephyrproject-rtos/nanopb
      revision: d148bd26718e4c10414f07a7eb1bd24c62e56c5d
      path: modules/lib/nanopb
    - name: net-tools
      url: https://github.com/zephyrproject-rtos/net-tools
      revision: f49bd1354616fae4093bf36e5eaee43c51a55127
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      url: https://github.com/zephyrproject-rtos/nrf_hw_models
      revision: a47e326ca772ddd14cc3b9d4ca30a9ab44ecca16
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      url: https://github.com/zephyrproject-rtos/open-amp
      revision: 6010f0523cbc75f551d9256cf782f173177acdef
      path: modules/lib/open-amp
    - name: openthread
      url: https://github.com/zephyrproject-rtos/openthread
      revision: 5d706547ebcb0a85e11412bcd88e80e2af98c74d
      path: modules/lib/openthread
    - name: segger
      url: https://github.com/zephyrproject-rtos/segger
      revision: 3a52ab222133193802d3c3b4d21730b9b1f1d2f6
      path: modules/debug/segger
      groups:
        - debug
    - name: sof
      url: https://github.com/zephyrproject-rtos/sof
      revision: 76feb11d1b8f425021b5691668af2250fee444ac
      path: modules/audio/sof
    - name: tflite-micro
      url: https://github.com/zephyrproject-rtos/tflite-micro
      revision: 9156d050927012da87079064db59d07f03b8baf6
      path: modules/lib/tflite-micro
    - name: tinycbor
      url: https://github.com/zephyrproject-rtos/tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
      path: modules/lib/tinycbor
    - name: tinycrypt
      url: https://github.com/zephyrproject-rtos/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: TraceRecorderSource
      url: https://github.com/zephyrproject-rtos/TraceRecorderSource
      revision: 36c577727642457b0db7274298a4b96558374832
      path: modules/debug/TraceRecorder
      groups:
        - debug
    - name: trusted-firmware-m
      url: https://github.com/zephyrproject-rtos/trusted-firmware-m
      revision: c74be3890c9d975976fde1b1a3b2f5742bec34c0
      path: modules/tee/tfm
      groups:
        - tee
  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
