manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: ac1bf1b6c67c7abef0c4613aefce8662f71a38e4
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: orb-mcu-messaging
      revision: 373914af23e3ab33a6ef0f64d3a6e3f39d75a8ab
      path: modules/orb-mcu-messaging
      groups: [internal]
    - name: open-orb-mcu-messaging
      revision: main
      path: modules/open-orb-mcu-messaging
      groups: [public]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
  self:
    path: orb
    import:
      # select groups in orb/utils/open/groups.yml, between [internal] and [public]
      - utils/open/groups.yml
