manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: 43f8397f2f9ccbfd2744bc383d9ac19ae1ff0cfc # Zephyr 4.1.0 + patches on worldcoin/zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
          - zcbor
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.31.0
    - name: orb-messages
      revision: fb0ae0765a7827451789897ebd69085a1b2aa8fe
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 0da6bab271385e952813bfcbef9ce9bf38b0f27a
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: c4cf5f29027f44fd5aad1d896df5840e10b08fd4
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb
    west-commands: utils/west-commands.yml

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  # `optional` is used to fetch nanopb from the Zephyr west manifest
  group-filter: [-internal, +optional]
