manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
    - name: memfault
      url-base: https://github.com/memfault
  defaults:
    remote: worldcoin
  projects:
    - name: zephyr
      revision: 447c41c0729c0cbb4ca9fb6357d592c55c65a7b4
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - segger
          - nanopb
          - hal_st
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      remote: memfault
      revision: 1.9.1
    - name: orb-messages
      revision: dd255ea4fcab8c0587a3a4892b9d6064c57e1634
      path: modules/orb-messages/public
    - name: priv-orb-messages
      revision: 62e024982e458b9a89c530f05b947de4f9d8213d
      path: modules/orb-messages
      groups: [internal]
    - name: plug-and-trust
      revision: beb0db6da441f8fd5becfab6c216c8d51aac8dbf
      path: modules/plug-and-trust
      groups: [internal]
  self:
    path: orb

  # by default, only public projects are built
  # if access is granted, enable internal projects
  # with `west config manifest.group-filter +internal`
  group-filter: [-internal]
