#pragma once

typedef enum {
    RET_SUCCESS = 0x00,
    RET_ERROR_INTERNAL = 0x01,
    RET_ERROR_NO_MEM = 0x02,
    RET_ERROR_NOT_FOUND = 0x03,
    RET_ERROR_INVALID_PARAM = 0x04,
    RET_ERROR_INVALID_STATE = 0x05,
    RET_ERROR_INVALID_ADDR = 0x06,
    RET_ERROR_BUSY = 0x07,
    RET_ERROR_OFFLINE = 0x08,
    RET_ERROR_FORBIDDEN = 0x09,
    RET_ERROR_TIMEOUT = 0x0A,
    RET_ERROR_NOT_INITIALIZED = 0x0B,
    RET_ERROR_ASSERT_FAILS = 0x0C,
    RET_ERROR_ALREADY_INITIALIZED = 0x0D,
    RET_ERROR_NOT_SUPPORTED = 0x0E,
    RET_ERROR_UNSAFE = 0x0F,
} ret_code_t;

const char *
ret_code_to_str(ret_code_t code);
