#ifndef FIRMWARE_ERRORS_H
#define FIRMWARE_ERRORS_H

typedef enum {
    RET_SUCCESS = 0x00,
    RET_ERROR_INTERNAL = 0x01,
    RET_ERROR_NO_MEM = 0x02,
    RET_ERROR_NOT_FOUND = 0x03,
    RET_ERROR_INVALID_PARAM = 0x04,
    RET_ERROR_INVALID_STATE = 0x05,
    RET_ERROR_INVALID_ADDR = 0x06,
    RET_ERROR_BUSY = 0x07,
    RET_ERROR_OFFLINE = 0x08,
    RET_ERROR_FORBIDDEN = 0x09,
    RET_ERROR_TIMEOUT = 0x0A,
    RET_ERROR_NOT_INITIALIZED = 0x0B,
    RET_ERROR_ASSERT_FAILS = 0x0C,
} ret_code_t;

#endif // FIRMWARE_ERRORS_H
