//
// Created by Cyril on 17/08/2021.
//

#ifndef ORB_FIRMWARE_ORB_APP_BOARDS_STM32F3DISCOVERY_PLATFORM_STM32F3XX_CLOCKS_H
#define ORB_FIRMWARE_ORB_APP_BOARDS_STM32F3DISCOVERY_PLATFORM_STM32F3XX_CLOCKS_H

void
SystemClock_Config(void);

#endif //ORB_FIRMWARE_ORB_APP_BOARDS_STM32F3DISCOVERY_PLATFORM_STM32F3XX_CLOCKS_H
