//
// Created by Cyril on 22/10/2021.
//

#ifndef ORB_FIRMWARE_APP_MAIN_SRC_STEPPER_MOTORS_MOTORS_TESTS_H
#define ORB_FIRMWARE_APP_MAIN_SRC_STEPPER_MOTORS_MOTORS_TESTS_H

void
motors_tests_init(void);

#endif //ORB_FIRMWARE_APP_MAIN_SRC_STEPPER_MOTORS_MOTORS_TESTS_H
