name: docker_build
on:
  push:
    paths:
      - utils/docker/Dockerfile
      - utils/docker/Makefile
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd utils/docker && make build
