name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/worldcoin/mcu-zephyr-build@sha256:dcc0e3cdb924cfb34da681909190a43a05128859da3e1b8e71210f1e33e58437
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB_AUTOMATION }}
          known_hosts: ${{ secrets.SSH_KNOW_HOSTS_GITHUB_AUTOMATION }}
      - run: west init -m git@github.com:worldcoin/proto2-firmware.git --mr main .
      - run: west update
      - uses: actions/checkout@v2
        with:
          path: "app_main"
      - run: cd app_main && west build

  check-format:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/worldcoin/mcu-zephyr-build@sha256:dcc0e3cdb924cfb34da681909190a43a05128859da3e1b8e71210f1e33e58437
    steps:
      - uses: actions/checkout@v2
      - run: pre-commit run --all-files --config utils/format/pre-commit-config.yaml
