#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
    echo "Usage: $0 <HEX_FILE> <HEX_FILE> [HEX_FILE...]"
    echo
    echo "Combine at least two hex files into one."
    echo "Writes to standard out."
    exit 1
fi

tmpfile=$(mktemp 2>/dev/null || mktemp -t 'mytmpfile')

for arg; do
    cat "$arg" >> "$tmpfile"
done

# sed -i doesn't expect the same args on macos and linux
# so this below is a universal command that will create another temporary file
sed '/^:00000001FF/d' "$tmpfile" > "${tmpfile}.tmp" && mv "${tmpfile}.tmp" "$tmpfile"

echo ':00000001FF' >> "$tmpfile"

cat "$tmpfile"
