/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    stm32f3xx_it.c
  * @brief   Interrupt Service Routines.
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under BSD 3-Clause license,
  * the "License"; You may not use this file except in compliance with the
  * License. You may obtain a copy of the License at:
  *                        opensource.org/licenses/BSD-3-Clause
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include <compilers.h>
#include "board.h"
#include "stm32f3xx_it.h"
#include "hardfault.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN TD */

/* USER CODE END TD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/* External variables --------------------------------------------------------*/
extern TIM_HandleTypeDef htim1;

/* USER CODE BEGIN EV */

/* USER CODE END EV */

/******************************************************************************/
/*           Cortex-M4 Processor Interruption and Exception Handlers          */
/******************************************************************************/
/**
  * @brief This function handles Non maskable interrupt.
  */
void
NMI_Handler(void)
{
    HALT_IF_DEBUGGING();

    // reset target
    HAL_NVIC_SystemReset();
}

/**
  * @brief This function handles Hard fault interrupt.
  */
void
HardFault_Handler(void)
{
    // jump to hardfault_handler_c with active stack pointer
    HARDFAULT_HANDLING_ASM();

    // reset target
    HAL_NVIC_SystemReset();
}

/**
  * @brief This function handles Memory management fault.
  * Typically generated by Memory Protection Unit
  * Execute from unsupported area
  */
void
MemManage_Handler(void)
{
    HALT_IF_DEBUGGING();

    // reset target
    HAL_NVIC_SystemReset();
}

/**
  * @brief This function handles Pre-fetch fault, memory access fault.
  * Can be: Storing outside of addressable area
  * Can be imprecise: fault might take place after the execution of the faulty instruction, due to caching
  */
void
BusFault_Handler(void)
{
    HALT_IF_DEBUGGING();

    // reset target
    HAL_NVIC_SystemReset();
}

/**
  * @brief This function handles Undefined instruction or illegal state.
  * Can be: Divide by 0, unaligned access
  */
void
UsageFault_Handler(void)
{
    HALT_IF_DEBUGGING();

    // reset target
    HAL_NVIC_SystemReset();
}

/**
  * @brief This function handles Debug monitor.
  */
void
DebugMon_Handler(void)
{
    HALT_IF_DEBUGGING();

    // reset target
    HAL_NVIC_SystemReset();
}

/******************************************************************************/
/* STM32F3xx Peripheral Interrupt Handlers                                    */
/* Add here the Interrupt Handlers for the used peripherals.                  */
/* For the available peripheral interrupt handler names,                      */
/* please refer to the startup file (startup_stm32f3xx.s).                    */
/******************************************************************************/




/**
  * @brief This function handles TIM1 update and TIM16 interrupts.
  */
void
TIM1_UP_TIM16_IRQHandler(void)
{
    /* USER CODE BEGIN TIM1_UP_TIM16_IRQn 0 */

    /* USER CODE END TIM1_UP_TIM16_IRQn 0 */
    HAL_TIM_IRQHandler(&htim1);
    /* USER CODE BEGIN TIM1_UP_TIM16_IRQn 1 */

    /* USER CODE END TIM1_UP_TIM16_IRQn 1 */
}

/* USER CODE BEGIN 1 */

/* USER CODE END 1 */
/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
