//
// Created by Cyril on 08/07/2021.
//

#ifndef WORLDCOIN_FIRMWARE_ORB_APP_BOARDS_ORB_V1_CONFIG_APP_CONFIG_H
#define WORLDCOIN_FIRMWARE_ORB_APP_BOARDS_ORB_V1_CONFIG_APP_CONFIG_H

#define COM_RX_BUFFER_SIZE          256
#define COM_TX_BUFFER_SIZE          256

#define SERIALIZER_QUEUE_SIZE       8
#define DESERIALIZER_QUEUE_SIZE     8

#endif //WORLDCOIN_FIRMWARE_ORB_APP_BOARDS_ORB_V1_CONFIG_APP_CONFIG_H
