name: worldcoin
channels:
  - litex-hub
  - memfault
  - conda-forge
dependencies:
  - make
  - python=3.11
  - cmake
  - pyserial
  - ccache
  - protobuf
  - ninja
  - pthread-stubs
  - gperf
  - clang-format
  - pre-commit
  - libusb
  - pip
  - pip:
      - west
      - pyserial
      - pyocd
      - crc16
      - puncover
      - anytree==2.8.0 # rom_report fails with 2.9.0
      - -r ../test/requirements.txt
      - -r ../../../bootloader/mcuboot/scripts/requirements.txt
      - -r ../../../zephyr/scripts/requirements.txt
variables:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
