name: worldcoin
channels:
  - fouge # for openocd on macos-arm64
  - litex-hub
  - memfault
  - conda-forge
dependencies:
  - make
  - python=3.9
  - cmake
  - gcc-arm-none-eabi
  - multi-arch-gdb
  - pyserial
  - ccache
  - protobuf
  - ninja
  - pthread-stubs
  - gperf
  - clang-format
  - pre-commit
  - libusb
  - openocd
  - pip
  - pip:
      - west
      - pyserial
      - pyocd
      - -r ../../../bootloader/mcuboot/scripts/requirements.txt
      - -r ../../../zephyr/scripts/requirements.txt
variables:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
