name: worldcoin
channels:
  - fouge # for openocd on macos-arm64
  - litex-hub
  - memfault
  - conda-forge
dependencies:
  - make
  - python=3.9
  - cmake
  - pyserial
  - ccache
  - protobuf
  - ninja
  - pthread-stubs
  - gperf
  - clang-format
  - pre-commit
  - libusb
  - openocd
  - multi-arch-gdb
  - pip
  - pip:
      - west
      - pyserial
      - pyocd
variables:
  ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
  GNUARMEMB_TOOLCHAIN_PATH: $(CONDA_PREFIX)
