name: worldcoin
channels:
  - fouge
  - memfault
  - conda-forge
dependencies:
  - make
  - python=3.9
  - conda-forge::cmake
  - pyserial
  - ccache
  - protobuf
  - gcc-arm-none-eabi
  - pthread-stubs
