name: worldcoin
dependencies:
  - make
  - python=3.13
  - pyserial
  - ccache
  - conda-forge::protobuf
  - ninja
  - pthread-stubs
  - gperf
  - clang-format
  - pre-commit
  - conda-forge::libusb
  - gnupg
  - pip
  - pip:
      - west
      - pyserial
      - pyocd
      - crc16
      - puncover
      - identify>=2.5.32
      - -r ../test/requirements.txt
      - -r ../../../../bootloader/mcuboot/scripts/requirements.txt
      - -r ../../../../zephyr/scripts/requirements.txt
variables:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
