name: worldcoin
channels:
  - fouge
  - litex-hub
  - memfault
  - conda-forge
dependencies:
  - make
  - python=3.9
  - conda-forge::cmake
  - pyserial
  - ccache
  - protobuf
  - gcc-arm-none-eabi
  - pthread-stubs
  - openocd
# Requirements for STM32 Secure Engine utility
  - pycryptodome
  - pycryptodomex
  - ecdsa
  - pyelftools
  - numpy
