name: Main MCU
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # Main MCU workflow
  build-pearl-main:
    name: Build for Pearl
    uses: ./.github/workflows/zephyr_build.yml
    with:
      board: pearl_main
      app_path: orb/main_board/app
    secrets:
      gh_token: ${{ secrets.GIT_HUB_TOKEN }}

  build-diamond-main:
    name: Build for Diamond
    uses: ./.github/workflows/zephyr_build.yml
    with:
      board: diamond_main
      app_path: orb/main_board/app
    secrets:
      gh_token: ${{ secrets.GIT_HUB_TOKEN }}
